### ISSUE TITLE
thi.ng/geom 0.0.777-dirty not found

### ISSUE THREAD

**Issue by quinkennedy** [learn-postspectacular/resonate-workshop-2015#3]
when running 'lein deps' I got the following

'''
Retrieving figwheel/figwheel/0.2.5/figwheel-0.2.5.jar from clojars
Retrieving clojure-complete/clojure-complete/0.2.3/clojure-complete-0.2.3.jar from clojars
Could not find artifact thi.ng:geom:jar:0.0.777-dirty in central (https://repo1.maven.org/maven2/)
Could not find artifact thi.ng:geom:jar:0.0.777-dirty in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
'''

I am not behind a proxy. I edited 'project.clj' to reference thi.ng/geom 0.0.777 instead, and 'lein deps' completed successfully.

**Comment by postspectacular** [comment]
Hiya, I know, I know... am busy working on 0.0.778 which fixes the issue we had with 777 and also uses a newer version of Clojurescript (in which I discovered [another bug](http://dev.clojure.org/jira/browse/CLJS-1216)).

Also see here: https://gitter.im/learn-postspectacular/resonate-workshop-2015?at=5530e1c608c7a53a4a1d9c80

Will let you know here when this is complete. Sorry about the delay...

**Comment by postspectacular** [comment]
geom 0.0.778 never happened and instead this project is now using 0.0.803 and everything works out of the box...
